# os:
#   - linux
# sudo: false
# before_script:
#   - git clone https://github.com/flutter/flutter.git -b stable --depth 1
#   - ./flutter/bin/flutter doctor
#   - ./flutter/bin/flutter packages get
# script:
#   - ./flutter/bin/flutter analyze --no-current-package --dartdocs $TRAVIS_BUILD_DIR/lib
#   - ./flutter/bin/cache/dart-sdk/bin/dartfmt -n ./lib --set-exit-if-changed
#   - ./flutter/bin/flutter test --coverage --coverage-path=lcov.info
# after_success:
#   - bash <(curl -s https://codecov.io/bash)
# cache:
#   directories:
#     - $HOME/.pub-cache


language: android
jdk: oraclejdk8
env:
  global:
    - ANDROID_TARGET=android-27
    - ANDROID_ABI=armeabi-v7a
android:
  components:
  - tools
  - platform-tools
  - build-tools-27.0.1
  - android-27
  - extra-android-m2repository
  - $ANDROID_TARGET
  - sys-img-${ANDROID_ABI}-${ANDROID_TARGET}
before_script:
  - cd example
  - git clone https://github.com/flutter/flutter.git -b stable --depth 1
  - ./flutter/bin/flutter doctor
  - ./flutter/bin/flutter packages get
script:
  - ./flutter/bin/flutter doctor
  - cd exa
  - ./flutter/bin/flutter build apk --split-per-abi
  # - ./android/.gradlew build
  # - ./gradlew build jacocoTestReport assembleAndroidTest
  # - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  # - emulator -avd test -no-skin -no-audio -no-window &
  # - android-wait-for-emulator
  # - adb shell setprop dalvik.vm.dexopt-flags v=n,o=v
  # - ./gradlew connectedCheck
  # - ./flutter/bin/flutter doctor
after_success:
  - bash <(curl -s https://codecov.io/bash)
cache:
  directories:
    - $HOME/.pub-cache